version: '3.8'

services:
  backend:
    container_name: engrain-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/docker-backend
      - /docker-backend/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"